name: Configuration
on:
  push:
jobs:
  validate:
    name: Validate Configuration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download slack-delegate-bot
      uses: docker://dpb587/gget
      with:
        args: --exec github.com/dpb587/slack-delegate-bot delegatebot=delegatebot-*-linux-amd64
    - name: Validate
      id: validate
      run: |
        ./delegatebot \
          --config=./config/*.yml \
          --config=config/default.delegatebot \
          validate
