name: push
on:
- push
jobs:
  push:
    name: Push
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build app
      run: |
        set -eu

        pwd
        ls -l

        # avoids google default credentials error during validation
        export PAIRIST_API_KEY=fake-token

        mkdir app

        curl -Lo app/slack-delegate-bot https://github.com/dpb587/slack-delegate-bot/releases/download/v0.7.0/delegatebot-0.7.0-linux-amd64
        echo "1f2db68e7cb1785a5419cface1ca5f0c4f76d83cff6aac299b6bfc6937a65786  app/slack-delegate-bot" | shasum -c

        echo 'exec ./slack-delegate-bot --config=config/*.yml --config=config/default.delegatebot ${COMMAND:-run}' > app/exec
        chmod +x app/*

        cat > app/cf.yml <<EOF
        applications:
        - name: cloudfoundry-slack-interrupt-bot
          memory: 32M
          instances: 1
          buildpack: https://github.com/cloudfoundry/binary-buildpack
          no-route: true
          command: ./exec
        EOF

        cp -rp config app/config

        cd app

        COMMAND=validate ./exec
    - name: cf auth
      uses: "dpb587/cf-action@master"
      with:
        api: ${{ secrets.CF_API_ENDPOINT }}
        organization: ${{ secrets.ORG }}
        space: ${{ secrets.SPACE }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: cf push
      # run: /usr/local/bin/cf push -f app/cf.yml
      run: find ~/.cf
